name: AIPromptCraft
options:
  bundleIdPrefix: com.baralabs.AIPromptCraft
  deploymentTarget:
    iOS: 18.0
targets:
  AIPromptCraft:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.baralabs.AIPromptCraft
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: X6JW9727Y6 # Replace with your Apple Developer Team ID
    scheme:
      testTargets: []
      gatherCoverageData: true
